services:
  emulator:
    container_name: servicebus-emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - type: bind
        source: ./config.json
        target: /ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
     - SQL_SERVER=sqledge
     - MSSQL_SA_PASSWORD="${MSSQL_SA_PASSWORD}"  # Password should be same as what is set for SQL Edge
     - ACCEPT_EULA=${ACCEPT_EULA}
     - SQL_WAIT_INTERVAL=${SQL_WAIT_INTERVAL} # Optional: Time in seconds to wait for SQL to be ready (default is 15 seconds)
    depends_on:
      - sqledge
    networks:
      - sb-emulator
  sqledge:
    container_name: sqledge
    image: mcr.microsoft.com/azure-sql-edge:latest
    networks:
      sb-emulator:      
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}

networks:
  sb-emulator:
    driver: bridge