name: Regression Test - AT22

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 1-5'

jobs:
  at22:
    permissions:
      contents: read
    uses: ./.github/workflows/regression-test-ATX.yml
    with:
      environment: AT22
    secrets: inherit
